#!/usr/bin/env python3
# Reference PreToolUse hook (see AGENTS-rules/enforced/suggested/generated-files-guard/).
# Matcher: edit|write. Asks for confirmation before hand-editing files that roxygen2
# generates: NAMESPACE and man/*.Rd. Edit the roxygen comments in R/*.R and run
# devtools::document() instead.
# Hooks fail open: if this script errors, the action proceeds.

import json
import os
import sys


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        sys.exit(0)

    if payload.get("tool_name") not in ("edit", "write"):
        sys.exit(0)

    tin = payload.get("tool_input", {}) or {}
    path = tin.get("file_path") or tin.get("path") or ""
    norm = path.replace("\\", "/")
    name = os.path.basename(norm)
    in_man = "/man/" in norm or norm.startswith("man/")

    if name == "NAMESPACE" or (in_man and name.endswith(".Rd")):
        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "ask",
                "permissionDecisionReason": (
                    "This file is generated by roxygen2 and a hand edit will be "
                    "overwritten. Edit the roxygen comments in R/*.R and run "
                    "devtools::document() instead, unless you mean to patch it: "
                    + path
                ),
            }
        }))
    sys.exit(0)


if __name__ == "__main__":
    main()
